// f1feeder-react/src/containers/DriverOverview.jsx
import React, { Component } from 'react';

import apiService from '../core/services/apiService';
import Driver from '../components/Driver';
import DriverRaces from '../components/DriverRaces';

export default class DriverOverviewComponent extends Component {
  state = {
    driver: null,
    races: null,
  };

  componentDidMount() {
    const driverId = this.props.match.params.id;
    apiService.getDriverDetails(driverId).then(driver => {
      this.setState({ driver });
    });
    apiService.getDriverRaces(driverId).then(races => {
      this.setState({ races });
    });
  }

  render() {
    return (
      <section id="main">
        <nav id="secondary" className="main-nav col-md-3">
          <Driver driver={this.state.driver} />
          <br />
          <a href="/" className="btn btn-default">
            Back to drivers list
          </a>
        </nav>
        <div className="main-content col-md-9">
          <DriverRaces races={this.state.races} />
        </div>
      </section>
    );
  }
}

// f1feeder-angularjs-vuejs/app/vuejs/components/driverOverview.vue
<template>
  <section v-if="driver" id="main">
    <nav id="secondary" class="main-nav col-md-3">
      <driver :driver="driver"></driver>
      <br/>
      <a href="./#/drivers" class="btn btn-default">Back to drivers list</a>
    </nav>
    <div class="main-content col-md-9">
      <driver-races :races="races"></driver-races>
    </div>
  </section>
</template>

<script>
import apiService from '../../core/services/apiService';
import Driver from './driver.vue';
import DriverRaces from './driverRaces.vue';

export default {
  props: {
    id: String,
  },
  components: {
    Driver,
    DriverRaces,
  },
  data() {
    return {
      driver: null,
      races: [],
    };
  },
  created() {
    apiService.getDriverDetails(this.id).then(driver => {
      this.driver = driver;
    });
    apiService.getDriverRaces(this.id).then(races => {
      this.races = races;
    });
  },
  // async/await version
  // async created() {
  //   this.driver = await apiService.getDriverDetails(this.id);
  //   this.races = await apiService.getDriverRaces(this.id);
  // },
};
</script>
