// f1feeder-angularjs-vuejs-cli/src/containers/driverOverview.vue
<template>
  <section v-if="driver" id="main">
    <nav id="secondary" class="main-nav col-md-3">
      <driver :driver="driver"></driver>
      <br/>
      <a href="./#/drivers" class="btn btn-default">Back to drivers list</a>
    </nav>
    <div class="main-content col-md-9">
      <driver-races :races="races"></driver-races>
    </div>
  </section>
</template>

<script>
import log from 'loglevel';
import apiService from '../core/services/apiService';
import Driver from '../components/driver.vue';
import DriverRaces from '../components/driverRaces.vue';

export default {
  props: {
    id: String,
  },
  components: {
    Driver,
    DriverRaces,
  },
  data() {
    return {
      driver: null,
      races: [],
    };
  },
  created() {
    log.info('loading data (VueJS)');
    apiService.getDriverDetails(this.id).then(driver => {
      this.driver = driver;
    });
    apiService.getDriverRaces(this.id).then(races => {
      this.races = races;
    });
  },
  // async/await version
  // async created() {
  //   this.driver = await apiService.getDriverDetails(this.id);
  //   this.races = await apiService.getDriverRaces(this.id);
  // },
};
</script>

// f1feeder-angularjs-ngx-cli/src/app/components/driverOverview.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import * as log from 'loglevel';
import apiService from '../../core/services/apiService';

@Component({
  selector: 'driver-overview',
  template: `
    <section *ngIf="driver" id="main">
      <nav id="secondary" class="main-nav col-md-3">
        <driver [driver]="driver"></driver>
        <br/>
        <a href="./#/drivers" class="btn btn-default">Back to drivers list</a>
      </nav>
      <div class="main-content col-md-9">
        <driver-races [races]="races"></driver-races>
      </div>
    </section>
  `,
})
export class DriverOverviewComponent implements OnInit {
  @Input() id;
  driver: any;
  races = [];

  ngOnInit() {
    log.info('loading data (Angular)');

    apiService.getDriverDetails(this.id).then(driver => {
      this.driver = driver;
      console.log(driver);
    });
    apiService.getDriverRaces(this.id).then(races => {
      this.races = races;
    });
  }
}
