// f1feeder-angularjs-vuejs/app/vuejs/components/driverOverview.vue
<template>
  <section v-if="driver" id="main">
    <nav id="secondary" class="main-nav col-md-3">
      <driver :driver="driver"></driver>
      <br/>
      <a href="./#/drivers" class="btn btn-default">Back to drivers list</a>
    </nav>
    <div class="main-content col-md-9">
      <driver-races :races="races"></driver-races>
    </div>
  </section>
</template>

<script>
import apiService from '../../core/services/apiService';
import Driver from './driver.vue';
import DriverRaces from './driverRaces.vue';

export default {
  props: {
    id: String,
  },
  components: {
    Driver,
    DriverRaces,
  },
  data() {
    return {
      driver: null,
      races: [],
    };
  },
  created() {
    apiService.getDriverDetails(this.id).then(driver => {
      this.driver = driver;
    });
    apiService.getDriverRaces(this.id).then(races => {
      this.races = races;
    });
  },
  // async/await version
  // async created() {
  //   this.driver = await apiService.getDriverDetails(this.id);
  //   this.races = await apiService.getDriverRaces(this.id);
  // },
};
</script>

// f1feeder-angularjs-react/app/components/driverOverview.jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types';

import { apiService } from '../services/apiService';
import Driver from './driver';
import DriverRaces from './driverRaces';

/* eslint-disable react/prop-types, react/prefer-stateless-function */
export default class DriverOverviewComponent extends Component {
  static propTypes = { id: PropTypes.string.isRequired };
  state = {
    driver: null,
    races: null,
  };

  componentDidMount() {
    apiService.getDriverDetails(this.props.id).then(data => {
      this.setState({
        driver: data.MRData.StandingsTable.StandingsLists[0].DriverStandings[0],
      });
    });
    apiService.getDriverRaces(this.props.id).then(data => {
      this.setState({
        races: data.MRData.RaceTable.Races,
      });
    });
  }

  render() {
    return (
      <section id="main">
        <nav id="secondary" className="main-nav col-md-3">
          <Driver driver={this.state.driver} />
          <br />
          <a href="./#/drivers" className="btn btn-default">
            Back to drivers list
          </a>
        </nav>
        <div className="main-content col-md-9">
          <DriverRaces races={this.state.races} />
        </div>
      </section>
    );
  }
}
